version: '3'
services:
  proxy_pool:
    build: .
    image: proxy_pool
    restart: always
    container_name: proxy_pool
    ports:
      - '5010:5010'
    environment:
      DB_CONN: 'redis://:RPcNZpRAguxM9bbqzoUp@101.43.112.119:6379/0'
